package es.ramondin.estadopedidos.model.views.client;

import es.ramondin.estadopedidos.model.views.common.ResumenPedidosVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 25 14:54:16 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ResumenPedidosVOClient extends ViewUsageImpl implements ResumenPedidosVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ResumenPedidosVOClient() {
    }

    public void limpiaCacheConnx() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"limpiaCacheConnx",null,null);
        return;
    }

    public void executeWithParamsEdit(Integer desdeAnoPed, Integer hastaAnoPed, Integer desdeFecha, Integer hastaFecha, Integer margenDias) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"executeWithParamsEdit",new String [] {"java.lang.Integer","java.lang.Integer","java.lang.Integer","java.lang.Integer","java.lang.Integer"},new Object[] {desdeAnoPed, hastaAnoPed, desdeFecha, hastaFecha, margenDias});
        return;
    }
}
