package es.ramondin.estadopedidos.model.views;

import es.ramondin.estadopedidos.model.views.common.EstadoPedidosVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 25 11:08:19 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EstadoPedidosVOImpl extends ViewObjectImpl implements EstadoPedidosVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EstadoPedidosVOImpl() {
    }
    
    public void limpiaCacheConnx() {
        String queryOrig = this.getQuery();
        
        this.setQuery("");
        this.executeQuery();
        
        this.setQuery(queryOrig);
    }
}
