package es.ramondin.estadopedidos.model.views;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 26 09:58:47 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ResumenPedidosVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Actividad {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getActividad();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setActividad((Integer)value);
            }
        }
        ,
        DescActividad {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getDescActividad();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setDescActividad((String)value);
            }
        }
        ,
        Famiestp {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getFamiestp();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setFamiestp((Integer)value);
            }
        }
        ,
        DescFamiestp {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getDescFamiestp();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setDescFamiestp((String)value);
            }
        }
        ,
        PedidosTotales {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getPedidosTotales();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setPedidosTotales((Integer)value);
            }
        }
        ,
        AdelantadoAceptado {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getAdelantadoAceptado();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setAdelantadoAceptado((Integer)value);
            }
        }
        ,
        Urgente {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getUrgente();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setUrgente((Integer)value);
            }
        }
        ,
        NoAdelantado {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getNoAdelantado();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setNoAdelantado((Integer)value);
            }
        }
        ,
        AdelantadoAceptadoRetrasado {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getAdelantadoAceptadoRetrasado();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setAdelantadoAceptadoRetrasado((Integer)value);
            }
        }
        ,
        NoAdelantadoRetrasado {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getNoAdelantadoRetrasado();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setNoAdelantadoRetrasado((Integer)value);
            }
        }
        ,
        AdelantadoPorcTrans {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getAdelantadoPorcTrans();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setAdelantadoPorcTrans((BigDecimal)value);
            }
        }
        ,
        UrgentePorcTrans {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getUrgentePorcTrans();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setUrgentePorcTrans((BigDecimal)value);
            }
        }
        ,
        NoAdelantadoPorcTrans {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getNoAdelantadoPorcTrans();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setNoAdelantadoPorcTrans((BigDecimal)value);
            }
        }
        ,
        AdelantadoRetrasadoPorcTrans {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getAdelantadoRetrasadoPorcTrans();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setAdelantadoRetrasadoPorcTrans((BigDecimal)value);
            }
        }
        ,
        NoAdelantadoRetrasadoPorcTrans {
            public Object get(ResumenPedidosVORowImpl obj) {
                return obj.getNoAdelantadoRetrasadoPorcTrans();
            }

            public void put(ResumenPedidosVORowImpl obj, Object value) {
                obj.setNoAdelantadoRetrasadoPorcTrans((BigDecimal)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ResumenPedidosVORowImpl object);

        public abstract void put(ResumenPedidosVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVIDAD = AttributesEnum.Actividad.index();
    public static final int DESCACTIVIDAD = AttributesEnum.DescActividad.index();
    public static final int FAMIESTP = AttributesEnum.Famiestp.index();
    public static final int DESCFAMIESTP = AttributesEnum.DescFamiestp.index();
    public static final int PEDIDOSTOTALES = AttributesEnum.PedidosTotales.index();
    public static final int ADELANTADOACEPTADO = AttributesEnum.AdelantadoAceptado.index();
    public static final int URGENTE = AttributesEnum.Urgente.index();
    public static final int NOADELANTADO = AttributesEnum.NoAdelantado.index();
    public static final int ADELANTADOACEPTADORETRASADO = AttributesEnum.AdelantadoAceptadoRetrasado.index();
    public static final int NOADELANTADORETRASADO = AttributesEnum.NoAdelantadoRetrasado.index();
    public static final int ADELANTADOPORCTRANS = AttributesEnum.AdelantadoPorcTrans.index();
    public static final int URGENTEPORCTRANS = AttributesEnum.UrgentePorcTrans.index();
    public static final int NOADELANTADOPORCTRANS = AttributesEnum.NoAdelantadoPorcTrans.index();
    public static final int ADELANTADORETRASADOPORCTRANS = AttributesEnum.AdelantadoRetrasadoPorcTrans.index();
    public static final int NOADELANTADORETRASADOPORCTRANS = AttributesEnum.NoAdelantadoRetrasadoPorcTrans.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ResumenPedidosVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Actividad.
     * @return the Actividad
     */
    public Integer getActividad() {
        return (Integer) getAttributeInternal(ACTIVIDAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Actividad.
     * @param value value to set the  Actividad
     */
    public void setActividad(Integer value) {
        setAttributeInternal(ACTIVIDAD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DescActividad.
     * @return the DescActividad
     */
    public String getDescActividad() {
        return (String) getAttributeInternal(DESCACTIVIDAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DescActividad.
     * @param value value to set the  DescActividad
     */
    public void setDescActividad(String value) {
        setAttributeInternal(DESCACTIVIDAD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Famiestp.
     * @return the Famiestp
     */
    public Integer getFamiestp() {
        return (Integer) getAttributeInternal(FAMIESTP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Famiestp.
     * @param value value to set the  Famiestp
     */
    public void setFamiestp(Integer value) {
        setAttributeInternal(FAMIESTP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DescFamiestp.
     * @return the DescFamiestp
     */
    public String getDescFamiestp() {
        return (String) getAttributeInternal(DESCFAMIESTP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DescFamiestp.
     * @param value value to set the  DescFamiestp
     */
    public void setDescFamiestp(String value) {
        setAttributeInternal(DESCFAMIESTP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PedidosTotales.
     * @return the PedidosTotales
     */
    public Integer getPedidosTotales() {
        return (Integer) getAttributeInternal(PEDIDOSTOTALES);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PedidosTotales.
     * @param value value to set the  PedidosTotales
     */
    public void setPedidosTotales(Integer value) {
        setAttributeInternal(PEDIDOSTOTALES, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AdelantadoAceptado.
     * @return the AdelantadoAceptado
     */
    public Integer getAdelantadoAceptado() {
        return (Integer) getAttributeInternal(ADELANTADOACEPTADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AdelantadoAceptado.
     * @param value value to set the  AdelantadoAceptado
     */
    public void setAdelantadoAceptado(Integer value) {
        setAttributeInternal(ADELANTADOACEPTADO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Urgente.
     * @return the Urgente
     */
    public Integer getUrgente() {
        return (Integer) getAttributeInternal(URGENTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Urgente.
     * @param value value to set the  Urgente
     */
    public void setUrgente(Integer value) {
        setAttributeInternal(URGENTE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NoAdelantado.
     * @return the NoAdelantado
     */
    public Integer getNoAdelantado() {
        return (Integer) getAttributeInternal(NOADELANTADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoAdelantado.
     * @param value value to set the  NoAdelantado
     */
    public void setNoAdelantado(Integer value) {
        setAttributeInternal(NOADELANTADO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AdelantadoAceptadoRetrasado.
     * @return the AdelantadoAceptadoRetrasado
     */
    public Integer getAdelantadoAceptadoRetrasado() {
        return (Integer) getAttributeInternal(ADELANTADOACEPTADORETRASADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AdelantadoAceptadoRetrasado.
     * @param value value to set the  AdelantadoAceptadoRetrasado
     */
    public void setAdelantadoAceptadoRetrasado(Integer value) {
        setAttributeInternal(ADELANTADOACEPTADORETRASADO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NoAdelantadoRetrasado.
     * @return the NoAdelantadoRetrasado
     */
    public Integer getNoAdelantadoRetrasado() {
        return (Integer) getAttributeInternal(NOADELANTADORETRASADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoAdelantadoRetrasado.
     * @param value value to set the  NoAdelantadoRetrasado
     */
    public void setNoAdelantadoRetrasado(Integer value) {
        setAttributeInternal(NOADELANTADORETRASADO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AdelantadoPorcTrans.
     * @return the AdelantadoPorcTrans
     */
    public BigDecimal getAdelantadoPorcTrans() {
        return (BigDecimal) getAttributeInternal(ADELANTADOPORCTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AdelantadoPorcTrans.
     * @param value value to set the  AdelantadoPorcTrans
     */
    public void setAdelantadoPorcTrans(BigDecimal value) {
        setAttributeInternal(ADELANTADOPORCTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UrgentePorcTrans.
     * @return the UrgentePorcTrans
     */
    public BigDecimal getUrgentePorcTrans() {
        return (BigDecimal) getAttributeInternal(URGENTEPORCTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UrgentePorcTrans.
     * @param value value to set the  UrgentePorcTrans
     */
    public void setUrgentePorcTrans(BigDecimal value) {
        setAttributeInternal(URGENTEPORCTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NoAdelantadoPorcTrans.
     * @return the NoAdelantadoPorcTrans
     */
    public BigDecimal getNoAdelantadoPorcTrans() {
        return (BigDecimal) getAttributeInternal(NOADELANTADOPORCTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoAdelantadoPorcTrans.
     * @param value value to set the  NoAdelantadoPorcTrans
     */
    public void setNoAdelantadoPorcTrans(BigDecimal value) {
        setAttributeInternal(NOADELANTADOPORCTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AdelantadoRetrasadoPorcTrans.
     * @return the AdelantadoRetrasadoPorcTrans
     */
    public BigDecimal getAdelantadoRetrasadoPorcTrans() {
        return (BigDecimal) getAttributeInternal(ADELANTADORETRASADOPORCTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AdelantadoRetrasadoPorcTrans.
     * @param value value to set the  AdelantadoRetrasadoPorcTrans
     */
    public void setAdelantadoRetrasadoPorcTrans(BigDecimal value) {
        setAttributeInternal(ADELANTADORETRASADOPORCTRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NoAdelantadoRetrasadoPorcTrans.
     * @return the NoAdelantadoRetrasadoPorcTrans
     */
    public BigDecimal getNoAdelantadoRetrasadoPorcTrans() {
        return (BigDecimal) getAttributeInternal(NOADELANTADORETRASADOPORCTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoAdelantadoRetrasadoPorcTrans.
     * @param value value to set the  NoAdelantadoRetrasadoPorcTrans
     */
    public void setNoAdelantadoRetrasadoPorcTrans(BigDecimal value) {
        setAttributeInternal(NOADELANTADORETRASADOPORCTRANS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
