package es.ramondin.estadopedidos.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 25 11:09:20 CEST 2014
// ---------------------------------------------------------------------
public interface EstadoPedidosVO extends ViewObject {
    void limpiaCacheConnx();
}
